/**
 * Build-time asset pipeline for the ContentFlow Blazor Web UI.
 *
 * Copies self-hosted fonts and generates a local Lucide SVG sprite so that no
 * runtime asset is ever fetched from a CDN. Run via `npm run build:assets`
 * (also invoked by `npm run build`).
 */
import { mkdir, readFile, writeFile, copyFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const projectRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const wwwroot = join(projectRoot, "wwwroot");
const nodeModules = join(projectRoot, "node_modules");

const fontsSource = join(nodeModules, "@fontsource-variable", "vazirmatn", "files");
const fontsTarget = join(wwwroot, "fonts", "vazirmatn");
const fontFiles = [
  "vazirmatn-arabic-wght-normal.woff2",
  "vazirmatn-latin-ext-wght-normal.woff2",
  "vazirmatn-latin-wght-normal.woff2",
];

const lucideIcons = [
  "home",
  "list",
  "menu",
  "layout-dashboard",
  "shopping-cart",
  "package",
  "settings",
  "log-out",
  "sun",
  "moon",
  "search",
  "user",
  "external-link",
];

async function copyFonts() {
  await mkdir(fontsTarget, { recursive: true });
  for (const file of fontFiles) {
    const source = join(fontsSource, file);
    if (!existsSync(source)) {
      throw new Error(`Missing font file: ${source}. Run 'npm ci' first.`);
    }
    await copyFile(source, join(fontsTarget, file));
  }
  console.log(`fonts: copied ${fontFiles.length} files -> wwwroot/fonts/vazirmatn`);
}

async function buildLucideSprite() {
  const iconsDir = join(nodeModules, "lucide-static", "icons");
  if (!existsSync(iconsDir)) {
    throw new Error(`Missing Lucide icons at ${iconsDir}. Run 'npm ci' first.`);
  }

  const symbols = [];
  for (const name of lucideIcons) {
    const file = join(iconsDir, `${name}.svg`);
    if (!existsSync(file)) {
      throw new Error(`Missing Lucide icon '${name}' at ${file}.`);
    }
    const svg = await readFile(file, "utf8");
    const match = svg.match(/<svg[^>]*viewBox="([^"]+)"[^>]*>([\s\S]*?)<\/svg>/);
    if (!match) {
      throw new Error(`Could not parse Lucide icon '${name}'.`);
    }
    const [, viewBox, inner] = match;
    const body = inner.replace(/<!--[\s\S]*?-->/g, "").trim();
    symbols.push(`  <symbol id="${name}" viewBox="${viewBox}">\n${body}\n  </symbol>`);
  }

  const sprite = [
    '<?xml version="1.0" encoding="UTF-8"?>',
    "<!-- Generated by scripts/build-assets.mjs. Lucide Icons (ISC License). Do not edit by hand. -->",
    '<svg xmlns="http://www.w3.org/2000/svg" style="display:none" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">',
    ...symbols,
    "</svg>",
    "",
  ].join("\n");

  const targetDir = join(wwwroot, "lib", "lucide");
  await mkdir(targetDir, { recursive: true });
  await writeFile(join(targetDir, "lucide-sprite.svg"), sprite, "utf8");
  console.log(`lucide: generated sprite with ${lucideIcons.length} icons -> wwwroot/lib/lucide/lucide-sprite.svg`);
}

await copyFonts();
await buildLucideSprite();
